### PR TITLE
SetParam Support Add

### PR DESCRIPTION
**Pull request by muratmirgun**
#1 done without test

### CODE REVIEW

**Comment by yakuter** [comment]
Thank you @muratmirgun. Please add test and fix conflicts ;)

**Review by yakuter — CHANGES_REQUESTED** [review]
Waiting for changes defined in comment

**Comment by muratmirgun** [comment]
I wrote the tests

**Review by yakuter — APPROVED** [review]
Thank you @muratmirgun for this great job. I want to add a note here.

Test are not unnecessary things. They need to be realistic and foresee all possible situations. We do not test only success situations but also failures. For example, I didn't see a test for special characters like "./&%]" I don't know what happens if a user add this characters as params.

Anyway, thanks a lot for PR.

**Comment by yakuter** [comment]
Closes #1

**Comment by muratmirgun** [comment]
my biggest problem with writing tests is that I have to pay more attention to this part. Thanks a lot, though.

**Pull request merged**
